name: Codecov + Codacy Workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build_and_test:
    name: Build python environment and run coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64

    - name: Install poetry
      run: pip install pipx && pipx install poetry

    - name: Install dependencies
      run: poetry install --no-root --with=dev

    - name: Run test w/ coverage
      run: poetry run coverage run -m pytest .

    - name: Gerenate coverage report
      run: poetry run coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        verbose: true

    # - name: Run Codacy coverage reporter
    #   uses: codacy/codacy-coverage-reporter-action@v1
    #   with:
    #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    #     coverage-reports: coverage.xml
