name: Codecov Workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build python environment
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: x64

    - name: Update pip
      run: python -m pip install -U pip

    - name: Install dev requirements
      run: pip install -r ./requirements.dev.txt

    - name: Install coverage
      run: pip install coverage

    - name: Run test w/ coverage
      run: coverage run --branch -m pytest .

    - name: Gerenate coverage report
      run: coverage xml --include=main.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        verbose: true
