name: Codecov + Codacy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build_and_test:
    name: Build python environment and run coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          architecture: x64

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          version: "0.11.13"
          python-version: "3.14"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests w/ coverage
        run: uv run coverage run -m pytest .

      - name: Gerenate coverage report
        run: uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          directory: ./
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN_DEPENDABOT || secrets.CODECOV_TOKEN }}

    # - name: Run Codacy coverage reporter
    #   uses: codacy/codacy-coverage-reporter-action@v1
    #   with:
    #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    #     coverage-reports: coverage.xml
